/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_main_java_org_photonvision_rknn_RknnJNI */

#ifndef _Included_src_main_java_org_photonvision_rknn_RknnJNI
#define _Included_src_main_java_org_photonvision_rknn_RknnJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_main_java_org_photonvision_rknn_RknnJNI
 * Method:    detect
 * Signature: (JIIF)[Lsrc/main/java/org/photonvision/rknn/RknnJNI/RknnResult;
 */
JNIEXPORT jobjectArray JNICALL Java_src_main_java_org_photonvision_rknn_RknnJNI_detect
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
