/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photonvision_rknn_RknnJNI */

#ifndef _Included_org_photonvision_rknn_RknnJNI
#define _Included_org_photonvision_rknn_RknnJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photonvision_rknn_RknnJNI
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_photonvision_rknn_RknnJNI_create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_photonvision_rknn_RknnJNI
 * Method:    destroy
 * Signature: (J)J
 */
JNIEXPORT void JNICALL Java_org_photonvision_rknn_RknnJNI_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_photonvision_rknn_RknnJNI
 * Method:    detect
 * Signature: (JJIIF)[Lorg/photonvision/rknn/RknnJNI/RknnResult;
 */
JNIEXPORT jobjectArray JNICALL Java_org_photonvision_rknn_RknnJNI_detect
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
